using System.Text.Json.Serialization;

namespace AWX.Resources
{
    /// <summary>
    /// Resource Type
    /// </summary>
    [JsonConverter(typeof(Json.EnumUpperCamelCaseStringConverter<ResourceType>))]
    public enum ResourceType
    {
        None,
        [ResourcePath("applications", typeof(ResultSet<Application>), Method = Method.GET, Description = "List Applications")]
        [ResourcePath("applications", typeof(Application), Method = Method.POST, Description = "Create an Applications")]
        [ResourceIdPath(typeof(ActivityStream), Method = Method.GET, Description = "Retrieve an Application")]
        [ResourceIdPath(typeof(ActivityStream), Method = Method.PUT, Description = "Update an Application")]
        [ResourceIdPath(typeof(ActivityStream), Method = Method.PATCH, Description = "Update an Application")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Application")]
        [ResourceSubPath("activity_stream", typeof(ActivityStream), Description = "List Activity Stream for an Application")]
        [ResourceSubPath("tokens", typeof(ResultSet<OAuth2AccessToken>), Method = Method.GET, Description = "List Access Tokens for an Application")]
        [ResourceSubPath("tokens", typeof(OAuth2AccessToken), Method = Method.POST, Description = "Create an Access Tokens for an Application")]
        OAuth2Application,
        [ResourcePath("tokens", typeof(ResultSet<OAuth2AccessToken>), Description = "List Access Tokens")]
        [ResourcePath("tokens", typeof(OAuth2AccessToken), Method = Method.POST, Description = "Create an Access Token")]
        [ResourceIdPath(Type = typeof(OAuth2AccessToken), Method = Method.GET, Description = "Retrieve an Access Token")]
        [ResourceIdPath(Type = typeof(OAuth2AccessToken), Method = Method.PUT, Description = "Update an Access Token")]
        [ResourceIdPath(Type = typeof(OAuth2AccessToken), Method = Method.PATCH, Description = "Update an Access Token")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Access Token")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Method = Method.GET, Description = "Delete an Access Token")]
        OAuth2AccessToken,
        [ResourcePath("instances", typeof(ResultSet<Instance>), Description = "List Instances")]
        [ResourcePath("instances", typeof(Instance), Method = Method.POST, Description = "Create an Instance")]
        [ResourceIdPath(Type = typeof(Instance), Method = Method.GET, Description = "Retrieve an Instance")]
        [ResourceIdPath(Type = typeof(Instance), Method = Method.PUT, Description = "Update an Instance")]
        [ResourceIdPath(Type = typeof(Instance), Method = Method.PATCH, Description = "Update an Instance")]
        [ResourceSubPath("health_check", Method = Method.GET, Description = "Health Check Data")]
        [ResourceSubPath("health_check", Method = Method.POST, Description = "Manually Initiate a Health Check")]
        [ResourceSubPath("install_bundle")]
        [ResourceSubPath("instance_groups", typeof(ResultSet<InstanceGroup>), Method = Method.GET, Description = "List Instance Groups for an Instance")]
        [ResourceSubPath("instance_groups", typeof(InstanceGroup), Method = Method.POST, Description = "Create an Instance Group for an Instance")]
        [ResourceSubPath("jobs", typeof(IUnifiedJob), Description = "List Unified jobs for an Instance")]
        [ResourceSubPath("pears", typeof(ResultSet<Instance>), Description = "List Instances for an Instace")]
        Instance,
        [ResourcePath("instance_groups", typeof(ResultSet<InstanceGroup>), Description = "List Instance Groups")]
        [ResourcePath("instance_groups", typeof(InstanceGroup), Method = Method.POST, Description = "Create an Instance Group")]
        [ResourceIdPath(Type = typeof(InstanceGroup), Method = Method.GET, Description = "Retrieve an Instance Group")]
        [ResourceIdPath(Type = typeof(InstanceGroup), Method = Method.PUT, Description = "Update an Instance Group")]
        [ResourceIdPath(Type = typeof(InstanceGroup), Method = Method.PATCH, Description = "Update an Instance Group")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Instance Group")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("instances", typeof(ResultSet<Instance>), Description = "List Instances for an Instance Group")]
        [ResourceSubPath("instances", typeof(Instance), Method = Method.POST, Description = "Create an Instance for an Instance Group")]
        [ResourceSubPath("jobs", typeof(ResultSet), Description = "List Unified jobs for an Instance Group")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Description = "List Roles for an Instance Group")]
        InstanceGroup,
        [ResourcePath("config", typeof(Config), Description = "Return various sitewide configuration settings")]
        [ResourcePath("config", Method = Method.POST, Description = "Install or update an existing license")]
        [ResourcePath("config", Method = Method.DELETE, Description = "Delete an existing license")]
        [ResourceSubPath("attach", IsSubPathOfId = false, Method = Method.POST)]
        [ResourceSubPath("subscriptions", IsSubPathOfId = false, Method = Method.POST)]
        Config,
        [ResourcePath("ping", typeof(Ping), Description = "Return some basic information about this instance")]
        Ping,
        [ResourcePath("settings", typeof(Setting))]
        Setting,
        [ResourcePath("dashboard", typeof(Dashboard), Description = "Show Dashboard Details")]
        [ResourceSubPath("graphs/jobs", typeof(JobStatisticsContainer), Description = "View Statistics for job Runs", IsSubPathOfId = false)]
        Dashboard,
        [ResourcePath("organizations", typeof(ResultSet<Organization>), Description = "List Organizations")]
        [ResourcePath("organizations", typeof(Organization), Method = Method.POST, Description = "Create an Organization")]
        [ResourceIdPath(typeof(Organization), Method = Method.GET, Description = "Retrieve an Organization")]
        [ResourceIdPath(typeof(Organization), Method = Method.PUT, Description = "Update an Organization")]
        [ResourceIdPath(typeof(Organization), Method = Method.PATCH, Description = "Update an Organization")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Organization")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Method = Method.GET, Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Method = Method.GET, Description = "List Activity Stream for an Organization")]
        [ResourceSubPath("admins", typeof(ResultSet<User>), Method = Method.GET, Description = "List Admin Users for an Organization")]
        [ResourceSubPath("admins", typeof(User), Method = Method.POST, Description = "Create an Admin User for an Organization")]
        [ResourceSubPath("applications", typeof(ResultSet<Application>), Method = Method.GET, Description = "List Applications for an Organization")]
        [ResourceSubPath("applications", typeof(Application), Method = Method.POST, Description = "Create an Application for an Organization")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Method = Method.GET, Description = "List Credentials for an Organization")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for an Organization")]
        [ResourceSubPath("execution_environments", typeof(ResultSet<ExecutionEnvironment>), Method = Method.GET, Description = "List Execution Environments for an Organization")]
        [ResourceSubPath("execution_environments", typeof(ExecutionEnvironment), Method = Method.POST, Description = "Create an Excecution Environment for an Organization")]
        [ResourceSubPath("galaxy_credentials", typeof(ResultSet<Credential>), Method = Method.GET, Description = "List Credentials for an Organization")]
        [ResourceSubPath("galaxy_credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for an Organization")]
        [ResourceSubPath("instance_groups", typeof(ResultSet<InstanceGroup>), Method = Method.GET, Description = "List Instance Groups for an Organization")]
        [ResourceSubPath("instance_groups", typeof(InstanceGroup), Method = Method.POST, Description = "Create an Instance Group for an Organization")]
        [ResourceSubPath("inventories", typeof(ResultSet<Inventory>), Method = Method.GET, Description = "List Inventories for an Organization")]
        [ResourceSubPath("job_templates", typeof(ResultSet<JobTemplate>), Method = Method.GET, Description = "List Job Templates for an Organization")]
        [ResourceSubPath("job_templates", typeof(JobTemplate), Method = Method.POST, Description = "Create a Job Template for an Organization")]
        [ResourceSubPath("notification_templates_approvals", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Organization")]
        [ResourceSubPath("notification_templates_approvals", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Organization")]
        [ResourceSubPath("notification_templates_error", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Organization")]
        [ResourceSubPath("notification_templates_error", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Organization")]
        [ResourceSubPath("notification_templates_started", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Organization")]
        [ResourceSubPath("notification_templates_started", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Organization")]
        [ResourceSubPath("notification_templates_success", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Organization")]
        [ResourceSubPath("notification_templates_success", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Organization")]
        [ResourceSubPath("notification_templates", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Organization")]
        [ResourceSubPath("notification_templates", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Organization")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Method = Method.GET, Description = "List Roles for an Organization")]
        [ResourceSubPath("projects", typeof(ResultSet<Project>), Method = Method.GET, Description = "List Projects for an Organization")]
        [ResourceSubPath("projects", typeof(Project), Method = Method.POST, Description = "Create a Project for an Organization")]
        [ResourceSubPath("teams", typeof(ResultSet<Team>), Method = Method.GET, Description = "List Teams for an Organization")]
        [ResourceSubPath("teams", typeof(Team), Method = Method.POST, Description = "Create a Team for an Organization")]
        [ResourceSubPath("users", typeof(ResultSet<User>), Method = Method.GET, Description = "List Users for an Organization")]
        [ResourceSubPath("users", typeof(User), Method = Method.POST, Description = "Create a User for an Organization")]
        [ResourceSubPath("workflow_job_templates", typeof(ResultSet<WorkflowJobTemplate>), Method = Method.GET, Description = "List Workflow Job Templates for an Organization")]
        [ResourceSubPath("workflow_job_templates", typeof(WorkflowJobTemplate), Method = Method.POST, Description = "Create a Workflow Job Template for an Organization")]
        Organization,
        [ResourcePath("me", typeof(ResultSet<User>), Method = Method.GET, Description = "Retrieve information about the current User")]
        Me,
        [ResourcePath("users", typeof(ResultSet<User>), Method = Method.GET, Description = "List Users")]
        [ResourcePath("users", typeof(User), Method = Method.POST, Description = "Create a User")]
        [ResourceIdPath(typeof(User), Method = Method.GET, Description = "Retrieve a User")]
        [ResourceIdPath(typeof(User), Method = Method.PUT, Description = "Update a User")]
        [ResourceIdPath(typeof(User), Method = Method.PATCH, Description = "Update a User")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a User")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a User")]
        [ResourceSubPath("admin_of_organizations", typeof(ResultSet<Organization>), Description = "List Organizations Administered by this User")]
        [ResourceSubPath("applications", typeof(ResultSet<Application>), Method = Method.GET, Description = "List Applications for a User")]
        [ResourceSubPath("applications", typeof(Application), Method = Method.POST, Description = "Create an Application for a User")]
        [ResourceSubPath("authorized_tokens", typeof(ResultSet<OAuth2AccessToken>), Method = Method.GET, Description = "List Access Tokens for a User")]
        [ResourceSubPath("authorized_tokens", typeof(OAuth2AccessToken), Method = Method.POST, Description = "Create an Access Token for a User")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Method = Method.GET, Description = "List Credentials for a User")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for a User")]
        [ResourceSubPath("organizations", typeof(ResultSet<Organization>), Method = Method.GET, Description = "List Organizations for a User")]
        [ResourceSubPath("personal_tokens", typeof(ResultSet<OAuth2AccessToken>), Method = Method.GET, Description = "List Access Tokens for a User")]
        [ResourceSubPath("personal_tokens", typeof(OAuth2AccessToken), Method = Method.POST, Description = "Create an Access Token for a User")]
        [ResourceSubPath("projects", typeof(ResultSet<Project>), Method = Method.GET, Description = "List Projects for a User")]
        [ResourceSubPath("roles", typeof(ResultSet<Role>), Method = Method.GET, Description = "List Roles for a User")]
        [ResourceSubPath("roles", typeof(Role), Method = Method.POST, Description = "Associate Roles with this User")]
        [ResourceSubPath("teams", typeof(ResultSet<Team>), Method = Method.GET, Description = "List Teams for a User")]
        [ResourceSubPath("tokens", typeof(ResultSet<OAuth2AccessToken>), Method = Method.GET, Description = "List Access Tokens for a User")]
        [ResourceSubPath("tokens", typeof(OAuth2AccessToken), Method = Method.POST, Description = "Create an Access Token for a User")]
        User,
        [ResourcePath("projects", typeof(ResultSet<Project>), Method = Method.GET, Description = "List Projects")]
        [ResourcePath("projects", typeof(Project), Method = Method.POST, Description = "Create a Project")]
        [ResourceIdPath(typeof(Project), Method = Method.GET, Description = "Retrieve a Project")]
        [ResourceIdPath(typeof(Project), Method = Method.PUT, Description = "Update a Project")]
        [ResourceIdPath(typeof(Project), Method = Method.PATCH, Description = "Update a Project")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Project")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Project")]
        [ResourceSubPath("copy", typeof(Dictionary<string, bool>), Description = "Determine if a Project can be copied")]
        [ResourceSubPath("copy", typeof(Project), Method = Method.POST, Description = "Copy a Project")]
        [ResourceSubPath("inventories", typeof(string[]), Description = "Retrieve inventory files for a Project")]
        [ResourceSubPath("notification_templates_error", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Project")]
        [ResourceSubPath("notification_templates_error", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Project")]
        [ResourceSubPath("notification_templates_started", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Project")]
        [ResourceSubPath("notification_templates_started", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Project")]
        [ResourceSubPath("notification_templates_success", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Project")]
        [ResourceSubPath("notification_templates_success", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Project")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Description = "List Roles for a Project")]
        [ResourceSubPath("playbooks", typeof(string[]), Description = "Retrieve Project Playbooks")]
        [ResourceSubPath("project_updates", typeof(ResultSet<ProjectUpdateJob>), Description = "List Project Updates for a Project")]
        [ResourceSubPath("schedules", typeof(ResultSet<Schedule>), Description = "List Schedules for a Project")]
        [ResourceSubPath("schedules", typeof(Schedule), Method = Method.POST, Description = "Create a Schedule for a Project")]
        [ResourceSubPath("scm_inventory_sources", typeof(ResultSet<InventorySource>), Description = "List Inventory Sources for a Project")]
        [ResourceSubPath("teams", typeof(ResultSet<Team>), Description = "List Teams for a Project")]
        [ResourceSubPath("update", typeof(Dictionary<string, bool>), Description = "Determine if a Project can be updated")]
        [ResourceSubPath("update", typeof(ProjectUpdateJob.Detail), Method = Method.POST, Description = "Update a Project")]
        Project,
        [ResourcePath("project_updates", typeof(ProjectUpdateJob), Description = "List Project Updates")]
        [ResourceIdPath(typeof(ProjectUpdateJob.Detail), Description = "Retrieve a Project Update")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Project Update")]
        [ResourceSubPath("cancel", typeof(Dictionary<string, bool>), Description = "Determine if a Project Update can be canceled")]
        [ResourceSubPath("cancel", Method = Method.POST, Description = "Cancel Project Update")]
        [ResourceSubPath("events", typeof(ResultSet<ProjectUpdateJobEvent>), Description = "List Project Update Events for a Project Update")]
        [ResourceSubPath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications for a Project Update")]
        [ResourceSubPath("scm_inventory_updates", typeof(ResultSet<InventoryUpdateJob>), Description = "List Inventory Updates for a Project Update")]
        [ResourceSubPath("stdout", typeof(JobLog), Description = "Retrieve Project Update Stdout")]
        ProjectUpdate,
        [ResourcePath("teams", typeof(ResultSet<Team>), Description = "List Teams")]
        [ResourcePath("teams", typeof(Team), Method = Method.POST, Description = "Create a Team")]
        [ResourceIdPath(typeof(Team), Method = Method.GET, Description = "Retrieve a Team")]
        [ResourceIdPath(typeof(Team), Method = Method.PUT, Description = "Update a Team")]
        [ResourceIdPath(typeof(Team), Method = Method.PATCH, Description = "Update a Team")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Team")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Team")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for a Team")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for a Team")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Description = "List Roles for a Team")]
        [ResourceSubPath("projects", typeof(ResultSet<Project>), Description = "List Projects for a Team")]
        [ResourceSubPath("roles", typeof(ResultSet<Role>), Description = "List Roles for a Team")]
        [ResourceSubPath("roles", typeof(Role), Method = Method.POST, Description = "Associate Roles with this Team")]
        [ResourceSubPath("users", typeof(ResultSet<User>), Description = "List Users for a Team")]
        [ResourceSubPath("users", typeof(User), Method = Method.POST, Description = "Create a User for a Team")]
        Team,
        [ResourcePath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials")]
        [ResourcePath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential")]
        [ResourceIdPath(typeof(Credential), Method = Method.GET, Description = "Retrieve a Credential")]
        [ResourceIdPath(typeof(Credential), Method = Method.PUT, Description = "Update a Credential")]
        [ResourceIdPath(typeof(Credential), Method = Method.PATCH, Description = "Update a Credential")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Credential")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Credential")]
        [ResourceSubPath("copy", typeof(Dictionary<string, bool>), Description = "Determine if a Credential can be copied")]
        [ResourceSubPath("copy", typeof(Project), Method = Method.POST, Description = "Copy a Credential")]
        [ResourceSubPath("input_sources", typeof(ResultSet<CredentialInputSource>), Description = "List Credential Input Sources for a Credential")]
        [ResourceSubPath("input_sources", typeof(CredentialInputSource), Method = Method.POST, Description = "Create a Credential Input Source for a Credential")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Description = "List Roles for a Credential")]
        [ResourceSubPath("owner_teams", typeof(ResultSet<Team>), Description = "List Teams for a Credential")]
        [ResourceSubPath("owner_users", typeof(ResultSet<User>), Description = "List Users for a Credential")]
        [ResourceSubPath("test", Description = "")]
        [ResourceSubPath("test", Method = Method.POST, Description = "")]
        Credential,
        [ResourcePath("crendential_types", typeof(ResultSet<CredentialType>), Description = "List Credential Types")]
        [ResourcePath("crendential_types", typeof(CredentialType), Method = Method.POST, Description = "Create a Credential Type")]
        [ResourceIdPath(typeof(CredentialType), Method = Method.GET, Description = "Retrieve a Credential Type")]
        [ResourceIdPath(typeof(CredentialType), Method = Method.PUT, Description = "Update a Credential Type")]
        [ResourceIdPath(typeof(CredentialType), Method = Method.PATCH, Description = "Update a Credential Type")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Credential Type")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Credential Type")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for a Credential Type")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for a Credential Type")]
        [ResourceSubPath("test", Description = "")]
        [ResourceSubPath("test", Method = Method.POST, Description = "")]
        CredentialType,
        [ResourcePath("constructed_inventories", typeof(ResultSet<ConstructedInventory>), Description = "List Inventories")]
        [ResourcePath("constructed_inventories", typeof(ConstructedInventory), Method = Method.POST, Description = "Create an Inventory")]
        [ResourceIdPath(typeof(ConstructedInventory), Method = Method.GET, Description = "Retrieve an Inventory ")]
        [ResourceIdPath(typeof(ConstructedInventory), Method = Method.PUT, Description = "Update an Inventory")]
        [ResourceIdPath(typeof(ConstructedInventory), Method = Method.PATCH, Description = "Update an Inventory")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Inventory")]
        ConstructedInventory,
        [ResourcePath("inventories", typeof(ResultSet<Inventory>), Description = "List Inventories")]
        [ResourcePath("inventories", typeof(Inventory), Method = Method.POST, Description = "List Inventories")]
        [ResourceIdPath(typeof(Inventory), Method = Method.GET, Description = "Retrieve an Inventory")]
        [ResourceIdPath(typeof(Inventory), Method = Method.PUT, Description = "Update an Inventory")]
        [ResourceIdPath(typeof(Inventory), Method = Method.PATCH, Description = "Update an Inventory")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Inventory")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for an Inventory")]
        [ResourceSubPath("ad_hoc_commands", typeof(ResultSet<AdHocCommand>), Description = "List Ad Hoc Commands for an Inventory")]
        [ResourceSubPath("ad_hoc_commands", typeof(AdHocCommand), Method = Method.POST, Description = "Create an Ad Hoc Command for an Inventory")]
        [ResourceSubPath("copy", typeof(Dictionary<string, bool>), Description = "Determine if a Credential can be copied")]
        [ResourceSubPath("copy", typeof(Project), Method = Method.POST, Description = "Copy an Inventory")]
        [ResourceSubPath("groups", typeof(ResultSet<Group>), Description = "List Groups for an Inventory")]
        [ResourceSubPath("groups", typeof(Group), Method = Method.POST, Description = "Create a Group for an Inventory")]
        [ResourceSubPath("hosts", typeof(ResultSet<Host>), Description = "List Hosts for an Inventory")]
        [ResourceSubPath("hosts", typeof(Host), Method = Method.POST, Description = "Create a Host for an Inventory")]
        [ResourceSubPath("input_inventories", typeof(ResultSet<Inventory>), Description = "List Inventories for an Inventory")]
        [ResourceSubPath("input_inventories", typeof(Inventory), Method = Method.POST, Description = "Create an Inventory for an Inventory")]
        [ResourceSubPath("inventory_sources", typeof(ResultSet<InventorySource>), Description = "List Invenotry Sources for an Inventory")]
        [ResourceSubPath("inventory_sources", typeof(InventorySource), Method = Method.POST, Description = "Create an Inventory Source for an Inventory")]
        [ResourceSubPath("job_templates", typeof(ResultSet<JobTemplate>), Description = "List Job Templates for an Inventory")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for an Inventory")]
        [ResourceSubPath("labels", typeof(Label), Method = Method.POST, Description = "Create a Label for an Inventory")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Description = "List Roles for an Inventory")]
        [ResourceSubPath("root_groups", typeof(ResultSet<Group>), Description = "List Root Groups for an Inventory")]
        [ResourceSubPath("root_groups", typeof(Group), Method = Method.POST, Description = "Create a Root Group for an Inventory")]
        [ResourceSubPath("script", Description = "Generate inventory group and host data as needed for an inventory script")]
        [ResourceSubPath("tree", Description = "Group Tree for an Inventory")]
        [ResourceSubPath("update_inventory_sources", Description = "")]
        [ResourceSubPath("update_inventory_sources", Method = Method.POST, Description = "Update Inventory Sources")]
        [ResourceSubPath("variable_data", typeof(Dictionary<string, object?>), Description = "Retrieve Inventory Variable Data")]
        [ResourceSubPath("variable_data", Method = Method.PUT, Description = "Update Inventory Variable Data")]
        [ResourceSubPath("variable_data", Method = Method.PATCH, Description = "Update Inventory Variable Data")]
        Inventory,
        [ResourcePath("inventory_sources", typeof(ResultSet<InventorySource>), Description = "List Inventory Sources")]
        [ResourcePath("inventory_sources", typeof(InventorySource), Method = Method.POST, Description = "Create an Inventory Source")]
        [ResourceIdPath(typeof(InventorySource), Method = Method.GET, Description = "Retrieve an Inventory Source")]
        [ResourceIdPath(typeof(InventorySource), Method = Method.PUT, Description = "Update an Inventory Source")]
        [ResourceIdPath(typeof(InventorySource), Method = Method.PATCH, Description = "Update an Inventory Source")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Inventory Source")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for an Inventory Source")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for an Inventory Source")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for an Inventory Source")]
        [ResourceSubPath("groups", typeof(ResultSet<Group>), Description = "List Groups for an Inventory Source")]
        [ResourceSubPath("groups", Method = Method.DELETE, Description = "Delete all Groups of this Inventory Source")]
        [ResourceSubPath("hosts", typeof(ResultSet<Host>), Description = "List Hosts for an Inventory Source")]
        [ResourceSubPath("hosts", Method = Method.DELETE, Description = "Delete all Hosts of this Inventory Source")]
        [ResourceSubPath("inventory_updates", typeof(ResultSet<InventoryUpdateJob>), Description = "List Inventory Updates for an Inventory Source")]
        [ResourceSubPath("notification_templates_error", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Inventory Source")]
        [ResourceSubPath("notification_templates_error", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Inventory Source")]
        [ResourceSubPath("notification_templates_started", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Inventory Source")]
        [ResourceSubPath("notification_templates_started", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Inventory Source")]
        [ResourceSubPath("notification_templates_success", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for an Inventory Source")]
        [ResourceSubPath("notification_templates_success", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for an Inventory Source")]
        [ResourceSubPath("schedules", typeof(ResultSet<Schedule>), Description = "List Schedules for an Inventory Source")]
        [ResourceSubPath("schedules", typeof(Schedule), Method = Method.POST, Description = "Create a Schedule for an Inventory Source")]
        [ResourceSubPath("update", typeof(Dictionary<string, bool>), Description = "Determine if the Inventory Source can be updated")]
        [ResourceSubPath("update", typeof(InventoryUpdateJob), Method = Method.POST, Description = "Update Inventory Source")]
        InventorySource,
        [ResourcePath("inventory_updates", typeof(ResultSet<InventoryUpdateJob>), Description = "List Inventory Update")]
        [ResourceIdPath(typeof(InventoryUpdateJob.Detail), Description = "Retrieve an Inventory Update")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Inventory Update")]
        [ResourceSubPath("cancel", typeof(Dictionary<string, bool>), Description = "Determine if an Inventory Update can be canceled")]
        [ResourceSubPath("cancel", Method = Method.POST, Description = "Cancel an Inventory Update")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for an Inventory Update")]
        [ResourceSubPath("events", typeof(ResultSet<InventoryUpdateJobEvent>), Description = "List Inventory Update Events for an Inventory Update")]
        [ResourceSubPath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications for an Inventory Update")]
        [ResourceSubPath("stdout", typeof(JobLog), Description = "Retrieve Inventory Update Stdout")]
        InventoryUpdate,
        [ResourcePath("groups", typeof(ResultSet<Group>), Description = "List Groups")]
        [ResourcePath("groups", typeof(Group), Method = Method.POST, Description = "Create a Group")]
        [ResourceIdPath(typeof(Group), Method = Method.GET, Description = "Retrieve a Group")]
        [ResourceIdPath(typeof(Group), Method = Method.PUT, Description = "Upate a Group")]
        [ResourceIdPath(typeof(Group), Method = Method.PATCH, Description = "Upate a Group")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Group")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Group")]
        [ResourceSubPath("ad_hoc_commands", typeof(ResultSet<AdHocCommand>), Description = "List Ad Hoc Commands for a Group")]
        [ResourceSubPath("ad_hoc_commands", typeof(AdHocCommand), Method = Method.POST, Description = "Create an Ad Hoc Commmand for a Group")]
        [ResourceSubPath("all_hosts", typeof(ResultSet<Host>), Description = "List All Hosts for a Group")]
        [ResourceSubPath("children", typeof(ResultSet<Group>), Description = "List Groups for a Group")]
        [ResourceSubPath("children", typeof(Group), Method = Method.POST, Description = "Create a Group for a Group")]
        [ResourceSubPath("hosts", typeof(ResultSet<Host>), Description = "List Groups for a Group")]
        [ResourceSubPath("hosts", typeof(Host), Method = Method.POST, Description = "Create a Host for a Group")]
        [ResourceSubPath("inventory_sources", typeof(ResultSet<InventorySource>), Description = "List Inventory Sources for a Group")]
        [ResourceSubPath("job_events", typeof(ResultSet<JobEvent>), Description = "List Job Events for a Group")]
        [ResourceSubPath("job_host_summaries", typeof(ResultSet<JobHostSummary>), Description = "List Job Host Summaries for a Group")]
        [ResourceSubPath("potential_children", typeof(ResultSet<Group>), Description = "List Potential Child Groups for a Group")]
        [ResourceSubPath("variable_data", typeof(Dictionary<string, object?>), Description = "Retrieve Group Variable Data")]
        [ResourceSubPath("variable_data", Method = Method.PUT, Description = "Update Group Variable Data")]
        [ResourceSubPath("variable_data", Method = Method.PATCH, Description = "Update Group Variable Data")]
        Group,
        [ResourcePath("hosts", typeof(ResultSet<Host>), Description = "List Hosts")]
        [ResourcePath("hosts", typeof(Host), Method = Method.POST, Description = "Create a Host")]
        [ResourceIdPath(typeof(Host), Method = Method.GET, Description = "Retrieve a Host")]
        [ResourceIdPath(typeof(Host), Method = Method.PUT, Description = "Upate a Host")]
        [ResourceIdPath(typeof(Host), Method = Method.PATCH, Description = "Upate a Host")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Host")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Host")]
        [ResourceSubPath("ad_hoc_command_events", typeof(ResultSet<AdHocCommandJobEvent>), Description = "List Ad Hoc Command Events for a Host")]
        [ResourceSubPath("ad_hoc_commands", typeof(ResultSet<AdHocCommand>), Description = "List Ad Hoc Commands for a Host")]
        [ResourceSubPath("ad_hoc_commands", typeof(AdHocCommand), Method = Method.POST, Description = "Create an Ad Hoc Commmand for a Host")]
        [ResourceSubPath("all_groups", typeof(ResultSet<Group>), Description = "List All Groups for a Host")]
        [ResourceSubPath("ansible_facts", typeof(Dictionary<string, object?>), Description = "Retrieve Ansible Facts for a Host")]
        [ResourceSubPath("groups", typeof(ResultSet<Group>), Description = "List Groups for a Host")]
        [ResourceSubPath("groups", typeof(Group), Method = Method.POST, Description = "Create a Group for a Host")]
        [ResourceSubPath("inventory_sources", typeof(ResultSet<InventorySource>), Description = "List Inventory Sources for a Host")]
        [ResourceSubPath("job_events", typeof(ResultSet<JobEvent>), Description = "List Job Events for a Host")]
        [ResourceSubPath("job_host_summaries", typeof(ResultSet<JobHostSummary>), Description = "List Job Host Summaries for a Host")]
        [ResourceSubPath("smart_inventories", typeof(ResultSet<Inventory>), Description = "List Smart Inventires for a Host")]
        [ResourceSubPath("variable_data", typeof(Dictionary<string, object?>), Description = "Retrieve Group Variable Data")]
        [ResourceSubPath("variable_data", Method = Method.PUT, Description = "Update Group Variable Data")]
        [ResourceSubPath("variable_data", Method = Method.PATCH, Description = "Update Group Variable Data")]
        Host,

        [ResourcePath("job_templates", typeof(ResultSet<JobTemplate>), Description = "List Job Templates")]
        [ResourcePath("job_templates", typeof(JobTemplate), Method = Method.POST, Description = "Create a Job Template")]
        [ResourceIdPath(Type = typeof(JobTemplate), Method = Method.GET, Description = "Retrieve a Job Template")]
        [ResourceIdPath(Type = typeof(JobTemplate), Method = Method.PUT, Description = "Update a Job Template")]
        [ResourceIdPath(Type = typeof(JobTemplate), Method = Method.PATCH, Description = "Update a Job Template")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Job Template")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Streams for a Job Template")]
        [ResourceSubPath("callback", Description = "")]
        [ResourceSubPath("callback", Method = Method.POST, Description = "")]
        [ResourceSubPath("copy", typeof(Dictionary<string, bool>), Description = "Determine a Job Template can be copied")]
        [ResourceSubPath("copy", typeof(JobTemplate), Description = "Copy a Job Template")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for a Job Template")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for a Job Template")]
        [ResourceSubPath("github", Method = Method.POST, Description = "")]
        [ResourceSubPath("gitlab", Method = Method.POST, Description = "")]
        [ResourceSubPath("instance_groups", typeof(ResultSet<InstanceGroup>), Description = "List Instance Groups for a Job Template")]
        [ResourceSubPath("instance_groups", typeof(InstanceGroup), Method = Method.POST, Description = "List Instance Groups for a Job Template")]
        [ResourceSubPath("jobs", typeof(ResultSet<JobTemplateJob>), Description = "List Jobs for a Job Template")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for a Job Template")]
        [ResourceSubPath("labels", typeof(Label), Method = Method.POST, Description = "Create a Label for a Job Template")]
        [ResourceSubPath("launch", typeof(JobTemplateLaunchRequirements), Description = "Get launch requrirements for a Job Template")]
        [ResourceSubPath("launch", typeof(JobTemplateJob.LaunchResult), Method = Method.POST, Description = "Launch a Job Template")]
        [ResourceSubPath("notification_templates_error", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Job Template")]
        [ResourceSubPath("notification_templates_error", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Job Template")]
        [ResourceSubPath("notification_templates_started", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Job Template")]
        [ResourceSubPath("notification_templates_started", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Job Template")]
        [ResourceSubPath("notification_templates_success", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Job Template")]
        [ResourceSubPath("notification_templates_success", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Job Template")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Description = "List Roles for a Job Template")]
        [ResourceSubPath("schedules", typeof(ResultSet<Schedule>), Description = "List Schedules for a Job Template")]
        [ResourceSubPath("schedules", typeof(Schedule), Method = Method.POST, Description = "Create a Schedule for a Job Template")]
        [ResourceSubPath("slice_workflow_jobs", typeof(ResultSet<WorkflowJob>), Description = "List Workflow Jobs for a Job Template")]
        [ResourceSubPath("slice_workflow_jobs", typeof(WorkflowJob), Method = Method.POST, Description = "Create a WorkflowJob for a Job Template")]
        [ResourceSubPath("survey_spec", typeof(Survey), Description = "Retrieve Survey Spec for a Job Template")]
        [ResourceSubPath("survey_spec", Method = Method.POST, Description = "Create Survey Spec for a Job Template")]
        [ResourceSubPath("survey_spec", Method = Method.DELETE, Description = "Delete Survey Spec for a Job Template")]
        [ResourceSubPath("webhook_key", typeof(Dictionary<string, string>), Description = "Retrieve Webhook Key for a Job Template")]
        [ResourceSubPath("webhook_key", typeof(Dictionary<string, string>), Method = Method.POST, Description = "Create a Webhook Key for a Job Template")]
        JobTemplate,

        [ResourcePath("jobs", typeof(ResultSet<JobTemplateJob>), Description = "List jobs")]
        [ResourceIdPath(Type = typeof(JobTemplateJob.Detail), Description = "Retrieve the detailed job.")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Request delete to the job.")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Job")]
        [ResourceSubPath("cancel", typeof(Dictionary<string, bool>), Description = "Determine if the job can be canceld.")]
        [ResourceSubPath("cancel", typeof(string), Method = Method.POST, Description = "Request cancel the pending or running job.")]
        [ResourceSubPath("create_schedule", Description = "Retrieve information about what proompts are and whether or not a schedule can be created")]
        [ResourceSubPath("create_schedule", Method = Method.POST, Description = "Create a Schedule based on a Job")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for a Job")]
        [ResourceSubPath("job_events", typeof(ResultSet<JobEvent>), Description = "List Job Events for a Job")]
        [ResourceSubPath("job_events/children_summary", Description = "View a summary of children events")]
        [ResourceSubPath("job_host_summaries", typeof(ResultSet<JobHostSummary>), Description = "List Job Host Summaries for a Job")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for a Job")]
        [ResourceSubPath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications for a Job")]
        [ResourceSubPath("relaunch", Description = "")]
        [ResourceSubPath("relaunch", Method = Method.POST, Description = "Relaunch a Job")]
        [ResourceSubPath("stdout", typeof(JobLog), Description = "Retrieve Job Stdout")]
        Job,
        [ResourcePath("job_events", typeof(JobEvent), Virtual = true)]
        [ResourceIdPath(typeof(JobEvent), Description = "Retrieve a Job Event")]
        [ResourceSubPath("children", Description = "List Job Events for a Job Event")]
        JobEvent,
        [ResourcePath("project_update_event", typeof(ProjectUpdateJobEvent), Virtual = true)]
        ProjectUpdateEvent,
        [ResourcePath("inventory_update_event", typeof(InventoryUpdateJobEvent), Virtual = true)]
        InventoryUpdateEvent,
        [ResourcePath("job_host_summaries", typeof(JobHostSummary), Virtual = true)]
        [ResourceIdPath(typeof(JobHostSummary), Description = "Retrieve a Job Host Summary")]
        JobHostSummary,
        [ResourcePath("ad_hoc_commands", typeof(ResultSet<AdHocCommand>), Description = "List Ad Hoc Commands")]
        [ResourcePath("ad_hoc_commands", typeof(AdHocCommandJobEvent), Method = Method.POST, Description = "Create an Ad Hoc Command")]
        [ResourceIdPath(typeof(AdHocCommand), Method = Method.GET, Description = "Retrieve an Ad Hoc Command")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Ad Hoc Command")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for an Ad Hoc Command")]
        [ResourceSubPath("cancel", typeof(Dictionary<string, bool>), Description = "Determine if the Ad Hoc Command can be cancled")]
        [ResourceSubPath("cancel", Method = Method.POST, Description = "Request cancel the pending or running Ad Hoc Command")]
        [ResourceSubPath("events", typeof(ResultSet<AdHocCommandJobEvent>), Description = "List Ac Hoc Command Events for an Ad Hoc Comand")]
        [ResourceSubPath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications for an Ad Hoc Command")]
        [ResourceSubPath("relaunch", Description = "")]
        [ResourceSubPath("relaunch", Method = Method.POST, Description = "Relaunch an Ad Hoc Command")]
        [ResourceSubPath("stdout", typeof(JobLog), Description = "Retrieve Ad Hoc Command Stdout")]
        AdHocCommand,
        [ResourcePath("ad_hoc_command_events", typeof(AdHocCommandJobEvent), Virtual = true)]
        AdHocCommandEvent,
        [ResourcePath("system_job_templates", typeof(ResultSet<SystemJobTemplate>), Description = "List System Job Templates")]
        [ResourceIdPath(typeof(SystemJobTemplate), Description = "Retrieve a System Job Template")]
        [ResourceSubPath("jobs", typeof(ResultSet<SystemJob>), Description = "List System Jobs for a System Job Template")]
        [ResourceSubPath("launch", Description = "")]
        [ResourceSubPath("launch", typeof(SystemJob), Method = Method.POST, Description = "Launch a System Job Template")]
        [ResourceSubPath("notification_templates_error", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a System Job Template")]
        [ResourceSubPath("notification_templates_error", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a System Job Template")]
        [ResourceSubPath("notification_templates_started", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a System Job Template")]
        [ResourceSubPath("notification_templates_started", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a System Job Template")]
        [ResourceSubPath("notification_templates_success", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a System Job Template")]
        [ResourceSubPath("notification_templates_success", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a System Job Template")]
        [ResourceSubPath("schedules", typeof(ResultSet<Schedule>), Description = "List Schedules for a System Job Template")]
        [ResourceSubPath("schedules", typeof(Schedule), Method = Method.POST, Description = "Create a Schedule for a System Job Template")]
        SystemJobTemplate,
        [ResourcePath("system_jobs", typeof(ResultSet<SystemJob>), Description = "List System Jobs")]
        [ResourceIdPath(typeof(SystemJob), Description = "Retrieve a System Job")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a System Job")]
        [ResourceSubPath("cancel", typeof(Dictionary<string, bool>), Description = "Determine if a System Job can be canceled")]
        [ResourceSubPath("cancel", Method = Method.POST, Description = "Request cancel the pending or running System Job")]
        [ResourceSubPath("events", typeof(ResultSet<SystemJobEvent>), Description = "List System Job Events for a System Job")]
        [ResourceSubPath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications for a System Job")]
        SystemJob,
        [ResourcePath("system_job_event", typeof(SystemJobEvent), Virtual = true)]
        SystemJobEvent,
        [ResourcePath("schedules", typeof(ResultSet<Schedule>), Description = "List Schedules")]
        [ResourcePath("schedules", typeof(Schedule), Method = Method.POST, Description = "Create a Schedule")]
        [ResourceIdPath(typeof(Schedule), Description = "Retrieve a Schedule")]
        [ResourceIdPath(typeof(Schedule), Method = Method.PUT, Description = "Update a Schedule")]
        [ResourceIdPath(typeof(Schedule), Method = Method.PATCH, Description = "Update a Schedule")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Schedule")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for a Schedule")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for a Schedule")]
        [ResourceSubPath("instance_groups", typeof(ResultSet<InstanceGroup>), Description = "List Instance Groups for a Schedule")]
        [ResourceSubPath("instance_groups", typeof(InstanceGroup), Method = Method.POST, Description = "Create an Instance Group for a Schedule")]
        [ResourceSubPath("jobs", typeof(ResultSet), Description = "List Unified Jobs for a Schedule")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for a Schedule")]
        [ResourceSubPath("labels", typeof(Label), Method = Method.POST, Description = "Create a Label for a Schedule")]
        [ResourceSubPath("preview", typeof(Dictionary<string, string[]>), Method = Method.POST, Description = "", IsSubPathOfId = false)]
        [ResourceSubPath("zoneinfo", typeof(Dictionary<string, string[]>), Description = "Retrieve Time Zone information", IsSubPathOfId = false)]
        Schedule,
        [ResourcePath("roles", typeof(ResultSet<Role>), Description = "List Roles")]
        [ResourceIdPath(typeof(Role), Description = "Retreive a Role")]
        [ResourceSubPath("children", typeof(ResultSet<Role>), Description = "List Roles for a Role")]
        [ResourceSubPath("parents", typeof(ResultSet<Role>), Description = "List Roles for a Role")]
        [ResourceSubPath("teams", typeof(ResultSet<Team>), Description = "List Teams for a Role")]
        [ResourceSubPath("teams", typeof(Team), Method = Method.POST, Description = "Create a Team for a Role")]
        [ResourceSubPath("users", typeof(ResultSet<User>), Description = "List Users for a Role")]
        [ResourceSubPath("users", typeof(User), Method = Method.POST, Description = "Create a User for a Role")]
        Role,
        [ResourcePath("notification_templates", typeof(ResultSet<NotificationTemplate>), Description = "List Notification Templates")]
        [ResourcePath("notification_templates", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template")]
        [ResourceIdPath(typeof(NotificationTemplate), Description = "Retrieve a Notification Template")]
        [ResourceIdPath(typeof(NotificationTemplate), Method = Method.PUT, Description = "Update a Notification Template")]
        [ResourceIdPath(typeof(NotificationTemplate), Method = Method.PATCH, Description = "Update a Notification Template")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Notification Template")]
        [ResourceSubPath("copy", typeof(Dictionary<string, bool>), Description = "Determine a Notification Template can be copied")]
        [ResourceSubPath("copy", typeof(JobTemplate), Description = "Copy a Notification Template")]
        [ResourceSubPath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications for a Notification Template")]
        [ResourceSubPath("test", Method = Method.POST, Description = "Test a Notification Template")]
        NotificationTemplate,
        [ResourcePath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications")]
        [ResourceIdPath(typeof(Notification), Description = "Retrieve a Notification")]
        Notification,
        [ResourcePath("labels", typeof(ResultSet<Label>), Description = "List Labels")]
        [ResourcePath("labels", typeof(Label), Method = Method.POST, Description = "Create a Label")]
        [ResourceIdPath(typeof(Label), Description = "Retrieve a Label")]
        [ResourceIdPath(typeof(Label), Method = Method.PUT, Description = "Update a Label")]
        [ResourceIdPath(typeof(Label), Method = Method.PATCH, Description = "Update a Label")]
        Label,
        [ResourcePath("unified_job_templates", typeof(ResultSet), Description = "List Unified Job Templates")]
        UnifiedJobTemplate,
        [ResourcePath("unified_jobs", typeof(ResultSet), Description = "List Unified Jobs")]
        UnifiedJob,
        [ResourcePath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream")]
        [ResourceIdPath(typeof(ActivityStream), Description = "Retrieve an Activity Stream")]
        ActivityStream,
        [ResourcePath("workflow_job_templates", typeof(ResultSet<WorkflowJobTemplate>), Description = "List Workflow Job Templates")]
        [ResourcePath("workflow_job_templates", typeof(WorkflowJobTemplate), Method = Method.POST, Description = "Create a Workflow Job Template")]
        [ResourceIdPath(typeof(WorkflowJobTemplate), Method = Method.GET, Description = "Retrieve a Workflow Job Template")]
        [ResourceIdPath(typeof(WorkflowJobTemplate), Method = Method.PUT, Description = "Update a Workflow Job Template")]
        [ResourceIdPath(typeof(WorkflowJobTemplate), Method = Method.PATCH, Description = "Update a Workflow Job Template")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Workflow Job Template")]
        [ResourceSubPath("access_list", typeof(ResultSet<User>), Description = "List Users")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Workflow Job Template")]
        [ResourceSubPath("copy", typeof(Dictionary<string, bool>), Description = "Determine a Notification Template can be copied")]
        [ResourceSubPath("copy", typeof(JobTemplate), Description = "Copy a Notification Template")]
        [ResourceSubPath("github", Method = Method.POST, Description = "")]
        [ResourceSubPath("gitlab", Method = Method.POST, Description = "")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for a Workflow Job Template")]
        [ResourceSubPath("labels", typeof(Label), Method = Method.POST, Description = "Create a Label for a Workflow Job Template")]
        [ResourceSubPath("launch", typeof(WorkflowJobTemplateLaunchRequirements), Description = "Get launch requrirements for a Workflow Job Template")]
        [ResourceSubPath("launch", typeof(WorkflowJob.LaunchResult), Method = Method.POST, Description = "Launch a Workflow Job Template")]
        [ResourceSubPath("notification_templates_approvals", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Workflow Job Template")]
        [ResourceSubPath("notification_templates_approvals", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Workflow Job Template")]
        [ResourceSubPath("notification_templates_error", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Workflow Job Template")]
        [ResourceSubPath("notification_templates_error", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Workflow Job Template")]
        [ResourceSubPath("notification_templates_started", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Workflow Job Template")]
        [ResourceSubPath("notification_templates_started", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Workflow Job Template")]
        [ResourceSubPath("notification_templates_success", typeof(ResultSet<NotificationTemplate>), Method = Method.GET, Description = "List Notification Templates for a Workflow Job Template")]
        [ResourceSubPath("notification_templates_success", typeof(NotificationTemplate), Method = Method.POST, Description = "Create a Notification Template for a Workflow Job Template")]
        [ResourceSubPath("object_roles", typeof(ResultSet<Role>), Description = "List Roles for a Workflow Job Template")]
        [ResourceSubPath("schedules", typeof(ResultSet<Schedule>), Description = "List Schedules for a Workflow Job Template")]
        [ResourceSubPath("schedules", typeof(Schedule), Method = Method.POST, Description = "Create a Schedule for a Workflow Job Template")]
        [ResourceSubPath("survey_spec", typeof(Survey), Description = "Retrieve Survey Spec for a Workflow Job Template")]
        [ResourceSubPath("survey_spec", Method = Method.POST, Description = "Create Survey Spec for a Workflow Job Template")]
        [ResourceSubPath("survey_spec", Method = Method.DELETE, Description = "Delete Survey Spec for a Workflow Job Template")]
        [ResourceSubPath("webhook_key", typeof(Dictionary<string, string>), Description = "Retrieve Webhook Key for a Workflow Job Template")]
        [ResourceSubPath("webhook_key", typeof(Dictionary<string, string>), Method = Method.POST, Description = "Create a Webhook Key for a Workflow Job Template")]
        [ResourceSubPath("workflow_jobs", typeof(ResultSet<WorkflowJob>), Description = "List Workflow Jobs for a Workflow Job Template")]
        [ResourceSubPath("workflow_nodes", typeof(ResultSet<WorkflowJobTemplateNode>), Description = "List Workflow Job Template Nodes")]
        [ResourceSubPath("workflow_nodes", typeof(WorkflowJobTemplateNode), Method = Method.POST, Description = "Create a Workflow Job Template Node")]
        WorkflowJobTemplate,
        [ResourcePath("workflow_jobs", typeof(ResultSet<WorkflowJob>), Description = "List Workflow Jobs")]
        [ResourceIdPath(typeof(WorkflowJob.Detail), Description = "Retrieve a Workflow Job")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Workflow Job")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for a Workflow Job")]
        [ResourceSubPath("cancel", typeof(Dictionary<string, bool>), Description = "Determine if a Workflow Job can be canceled")]
        [ResourceSubPath("cancel", Method = Method.POST, Description = "Request cancel the pending or running Workflow Job")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for a Workflow Job")]
        [ResourceSubPath("notifications", typeof(ResultSet<Notification>), Description = "List Notifications for a Workflow Job")]
        [ResourceSubPath("relaunch", Description = "")]
        [ResourceSubPath("relaunch", Method = Method.POST, Description = "Relaunch a Workflow Job")]
        [ResourceSubPath("workflow_nodes", typeof(ResultSet<WorkflowJobNode>), Description = "List Workflow Job Nodes for a Workflow Job")]
        WorkflowJob,
        [ResourcePath("workflow_job_template_nodes", typeof(ResultSet<WorkflowJobTemplateNode>), Description = "List Workflow Job Template Nodes")]
        [ResourcePath("workflow_job_template_nodes", typeof(WorkflowJobTemplateNode), Method = Method.POST, Description = "Create a Workflow Job Template Node")]
        [ResourceIdPath(typeof(WorkflowJobTemplateNode), Method = Method.GET, Description = "Retrieve a Workflow Job Template Node")]
        [ResourceIdPath(typeof(WorkflowJobTemplateNode), Method = Method.PUT, Description = "Update a Workflow Job Template Node")]
        [ResourceIdPath(typeof(WorkflowJobTemplateNode), Method = Method.PATCH, Description = "Update a Workflow Job Template Node")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Workflow Job Template Node")]
        [ResourceSubPath("always_nodes", typeof(ResultSet<WorkflowJobTemplateNode>), Description = "List Workflow Job Templates for a Workflow Job Template Node")]
        [ResourceSubPath("always_nodes", typeof(WorkflowJobTemplateNode), Method = Method.POST, Description = "Create a Workflow Job Template for a Workflow Job Template Node")]
        [ResourceSubPath("create_approval_template", Description = "List Workflow Job Templates for a Workflow Job Template Node")]
        [ResourceSubPath("create_approval_template", typeof(WorkflowApprovalTemplate), Method = Method.POST, Description = "Create a Workflow Approval Template for a Workflow Job Template Node")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for a Workflow Job Template Node")]
        [ResourceSubPath("credentials", typeof(Credential), Method = Method.POST, Description = "Create a Credential for a Workflow Job Template Node")]
        [ResourceSubPath("failure_nodes", typeof(ResultSet<WorkflowJobTemplateNode>), Description = "List Workflow Job Templates for a Workflow Job Template Node")]
        [ResourceSubPath("failure_nodes", typeof(WorkflowJobTemplateNode), Method = Method.POST, Description = "Create a Workflow Job Template for a Workflow Job Template Node")]
        [ResourceSubPath("instance_groups", typeof(ResultSet<InstanceGroup>), Description = "List Instance Groups for a Workflow Job Template Node")]
        [ResourceSubPath("instance_groups", typeof(InstanceGroup), Method = Method.POST, Description = "Create a Instance Group for a Workflow Job Template Node")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for a Workflow Job Template Node")]
        [ResourceSubPath("labels", typeof(Label), Method = Method.POST, Description = "Create a Label for a Workflow Job Template Node")]
        [ResourceSubPath("success_nodes", typeof(ResultSet<WorkflowJobTemplateNode>), Description = "List Workflow Job Templates for a Workflow Job Template Node")]
        [ResourceSubPath("success_nodes", typeof(WorkflowJobTemplateNode), Method = Method.POST, Description = "Create a Workflow Job Template for a Workflow Job Template Node")]
        WorkflowJobTemplateNode,
        [ResourcePath("workflow_job_nodes", typeof(ResultSet<WorkflowJobNode>), Description = "List Workflow Job Nodes")]
        [ResourceIdPath(typeof(WorkflowJobNode), Description = "Retrieve a Workflow Job Node")]
        [ResourceSubPath("always_nodes", typeof(ResultSet<WorkflowJobNode>), Description = "List Workflow Job Nodes for a Workflow Job Node")]
        [ResourceSubPath("credentials", typeof(ResultSet<Credential>), Description = "List Credentials for a Workflow Job Node")]
        [ResourceSubPath("failure_nodes", typeof(ResultSet<WorkflowJobNode>), Description = "List Workflow Job Nodes for a Workflow Job Node")]
        [ResourceSubPath("instance_groups", typeof(ResultSet<InstanceGroup>), Description = "List Instance Groups for a Workflow Job Node")]
        [ResourceSubPath("instance_groups", typeof(InstanceGroup), Method = Method.POST, Description = "Create a Instance Group for a Workflow Job Node")]
        [ResourceSubPath("labels", typeof(ResultSet<Label>), Description = "List Labels for a Workflow Job Node")]
        [ResourceSubPath("success_nodes", typeof(ResultSet<WorkflowJobNode>), Description = "List Workflow Job Nodes for a Workflow Job Node")]
        WorkflowJobNode,
        // Analytices,
        // Bulk
        [ResourcePath("credential_input_sources", typeof(ResultSet<CredentialInputSource>), Description = "List Credential Input Sources")]
        [ResourcePath("credential_input_sources", typeof(CredentialInputSource), Method = Method.POST, Description = "Create a Credential Input Source")]
        [ResourceIdPath(typeof(CredentialInputSource), Method = Method.GET, Description = "Retrieve a Credential Input Source")]
        [ResourceIdPath(typeof(CredentialInputSource), Method = Method.PUT, Description = "Update a Credential Input Source")]
        [ResourceIdPath(typeof(CredentialInputSource), Method = Method.PATCH, Description = "Update a Credential Input Source")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Credential Input Source")]
        CredentialInputSource,
        [ResourcePath("execution_environments", typeof(ResultSet<ExecutionEnvironment>), Description = "List Execution Environments")]
        [ResourcePath("execution_environments", typeof(ExecutionEnvironment), Method = Method.POST, Description = "Create an Execution Environment")]
        [ResourceIdPath(typeof(ExecutionEnvironment), Method = Method.GET, Description = "Retrieve an Execution Environment")]
        [ResourceIdPath(typeof(ExecutionEnvironment), Method = Method.PUT, Description = "Update an Execution Environment")]
        [ResourceIdPath(typeof(ExecutionEnvironment), Method = Method.PATCH, Description = "Update an Execution Environment")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete an Execution Environment")]
        [ResourceSubPath("activity_stream", typeof(ResultSet<ActivityStream>), Description = "List Activity Stream for an Execution Environment")]
        [ResourceSubPath("copy", typeof(Dictionary<string, bool>), Description = "Determine an Execution Environment can be copied")]
        [ResourceSubPath("copy", typeof(ExecutionEnvironment), Description = "Copy an Execution Environment")]
        [ResourceSubPath("unified_job_templates", typeof(ResultSet), Description = "List Unified Job Templates for an Execution Environment")]
        ExecutionEnvironment,
        [ResourcePath("host_metrics", typeof(ResultSet<HostMetric>), Description = "List Host Metrics")]
        [ResourceIdPath(typeof(HostMetric), Description = "Retrieve a Host Metric")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Host Metric")]
        HostMetrics,
        [ResourcePath("metrics", typeof(ResultSet<Metrics>), Description = "Show Metrics Details")]
        Metrics,
        [ResourcePath("workflow_approval_templates", Virtual = true)]
        [ResourceIdPath(typeof(WorkflowApprovalTemplate), Method = Method.GET, Description = "Retrieve a Workflow Approval Template")]
        [ResourceIdPath(typeof(WorkflowApprovalTemplate), Method = Method.PUT, Description = "Update a Workflow Approval Template")]
        [ResourceIdPath(typeof(WorkflowApprovalTemplate), Method = Method.PATCH, Description = "Update a Workflow Approval Template")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Workflow Approval Template")]
        [ResourceSubPath("approvals", typeof(ResultSet<WorkflowApproval>), Description = "List Workflow Approvals for a Workflow Approval Template")]
        WorkflowApprovalTemplate,
        [ResourcePath("workflow_approvals", typeof(ResultSet<WorkflowApproval>), Description = "List Workflow Approvals")]
        [ResourceIdPath(typeof(WorkflowApproval.Detail), Method = Method.GET, Description = "Retrieve a Workflow Approval")]
        [ResourceIdPath(Method = Method.DELETE, Description = "Delete a Workflow Approval")]
        [ResourceSubPath("approve", typeof(Dictionary<string, string>), Description = "Retrieve a Workflow Approval")]
        [ResourceSubPath("approve", Method = Method.POST, Description = "Retrieve a Workflow Approval")]
        [ResourceSubPath("deny", typeof(Dictionary<string, string>), Description = "Retrieve a Workflow Approval")]
        [ResourceSubPath("deny", Method = Method.POST, Description = "Retrieve a Workflow Approval")]
        WorkflowApproval,
    }


    [AttributeUsage(AttributeTargets.Enum | AttributeTargets.Field, AllowMultiple = true)]
    public class ResourcePathAttribute : Attribute
    {
        public ResourcePathAttribute(string pathName, Type resourceType)
        {
            PathName = pathName;
            Type = resourceType;
        }
        public ResourcePathAttribute(string pathName)
        {
            PathName = pathName;
        }
        public Method Method { get; init; } = Method.GET;
        public string PathName { get; set; }
        public Type? Type { get; init; } = null;
        public string Description { get; init; } = string.Empty;
        public bool Virtual { get; init; } = false;
    }

    [AttributeUsage(AttributeTargets.Enum | AttributeTargets.Field, AllowMultiple = true)]
    public abstract class ResourceSubPathBase : Attribute
    {
        public Type Type { get; init; } = typeof(string);
        public Method Method { get; init; } = Method.GET;
        public string Description { get; init; } = string.Empty;
    }

    [AttributeUsage(AttributeTargets.Enum | AttributeTargets.Field, AllowMultiple = true)]
    public class ResourceIdPathAttribute : ResourceSubPathBase
    {
        public ResourceIdPathAttribute() { }
        public ResourceIdPathAttribute(Type type)
        {
            Type = type;
        }
    }

    [AttributeUsage(AttributeTargets.Enum | AttributeTargets.Field, AllowMultiple = true)]
    public class ResourceSubPathAttribute : ResourceSubPathBase
    {
        public ResourceSubPathAttribute(string pathName)
        {
            PathName = pathName;
        }
        public ResourceSubPathAttribute(string pathName, Type type)
        {
            PathName = pathName;
            Type = type;
        }

        public string PathName { get; init; } = string.Empty;
        public bool IsSubPathOfId { get; init; } = true;
    }

}
